# Generated by Django 2.0.2 on 2018-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='CSE Block', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue',
            field=models.CharField(default='CSE Lab1', max_length=500),
            preserve_default=False,
        ),
    ]
