# Generated by Django 2.0.2 on 2018-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='additional_data',
            field=models.TextField(null=True),
        ),
    ]
