# Generated by Django 2.0.2 on 2018-02-26 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.RemoveField(
            model_name='eventvolunteer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='head',
        ),
        migrations.AddField(
            model_name='eventvolunteer',
            name='organizer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='EventManagement.Organizer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
