# Generated by Django 2.0.2 on 2018-02-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RituAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('EventManagement.volunteer',),
        ),
    ]
