# Generated by Django 2.0.2 on 2018-02-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0002_rituadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=999, max_length=15),
            preserve_default=False,
        ),
    ]
