# Generated by Django 2.0.2 on 2018-02-25 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0003_volunteer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
