# Generated by Django 2.0.2 on 2018-02-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagement', '0003_auto_20180226_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_team_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_team_event',
            field=models.BooleanField(default=False),
        ),
    ]
